services:
  - type: web
    name: frontend-project-12
    env: node
    region: oregon
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production