services:
  - type: web
    name: frontend-project-12
    env: node
    buildCommand: npm install --prefix frontend && npm run build --prefix frontend
    startCommand: echo "Starting @hexlet/chat-server..." && npm run start-server
    publish:
      path: frontend/build
    plan: free
