services:
  - type: web
    name: frontend-project-12
    env: node
    buildCommand: npm install && cd frontend && npm install && npm run build
    startCommand: npx start-server -s ./frontend/build
    publish:
      path: frontend/build
    plan: free
